//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public Alumno()
        {
        }

        public Alumno(int nMatricula)
        {
            NMatricula = nMatricula;
        }

        public Alumno(int nMatricula, string nombre, string telefono, bool aprobado, string idCiclo) : this(nMatricula)
        {
            Nombre = nombre;
            Telefono = telefono;
            Aprobado = aprobado;
            IdCiclo = idCiclo;
        }

        public int NMatricula { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public bool Aprobado { get; set; }
        public string IdCiclo { get; set; }
    
        public virtual Ciclo Ciclo { get; set; }
        public virtual FCT FCT { get; set; }

        public override bool Equals(object obj)
        {
            return obj is Alumno alumno &&
                   NMatricula == alumno.NMatricula;
        }
    }
}
