//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class FCT
    {
        public FCT()
        {
        }

        public FCT(int nMatricula, int idEmpresa)
        {
            NMatricula = nMatricula;
            IdEmpresa = idEmpresa;
        }

        public FCT(int nMatricula, int idEmpresa, string tutorInsti, string tutorEmpresa) : this(nMatricula, idEmpresa)
        {
            TutorInsti = tutorInsti;
            TutorEmpresa = tutorEmpresa;
        }

        public int NMatricula { get; set; }
        public int IdEmpresa { get; set; }
        public string TutorInsti { get; set; }
        public string TutorEmpresa { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Profe Profe { get; set; }

        public override bool Equals(object obj)
        {
            return obj is FCT fCT &&
                   NMatricula == fCT.NMatricula &&
                   IdEmpresa == fCT.IdEmpresa;
        }
    }
}
